{% set version = "0.9-8-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-disordr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/disordR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/disordR/disordR_{{ version }}.tar.gz
  sha256: 973d2b2703e2242a93d5b7e80414a9fa8e2bf54f180303bfcd972df53b7d8901

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-digest
  run:
    - r-base
    - r-matrix
    - r-digest

test:
  commands:
    - $R -e "library('disordR')"           # [not win]
    - "\"%R%\" -e \"library('disordR')\""  # [win]

about:
  home: https://github.com/RobinHankin/disordR
  license: GPL-2.0-or-later
  summary: Functionality for manipulating values of associative maps.  Ordinary R vectors are unsuitable for working with values of associative maps because elements of an R vector may be accessed by reference to their location in the vector, but associative maps are stored in arbitrary order.  However, when associating
    keys with values one needs both parts to be in 1-1 correspondence, so one cannot dispense with the order entirely.  The 'disordR' package includes a single S4 class, disord.  This class allows one to perform only those operations appropriate for manipulating values of associative maps and prevents any other operation
    (such as accessing an element at a particular location).  A useful heuristic is that one is only allowed to access or modify a disord object using a python list comprehension.  The idea is to prevent ill-defined operations on values (or keys) of associative maps, whose order is undefined or at best implementation-specific,
    while allowing and facilitating sensible operations.  The package is needed for development versions of 'mvp', 'hyper2', 'spray', 'clifford', and 'freealg'.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
